name: My First Action
on:
  push:
    branches:
      - main


jobs:
  Terraform-Job:
    name: My first job
    runs-on: dhondu-maharaj
    steps: 
      - name: Checkout
        uses: actions/checkout@v6.0.1


  
  
   

  


          
    

    
