name: My First Action
on:
  push:
    branches:
      - main


jobs:
  Terraform-Job:
    name: My first job
    runs-on: dhondu-maharaj
    steps: 
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
  
         version: 4.57.0
          

     
  
  
   
          


  
  
   

  


          
    

    
